### PR TITLE
Fix closing a camera not closing the associated track

### LINKED ISSUE #379: "panic: send on closed channel" after call Close on peerConnection
### Your environment.
  - Version: github.com/pion/mediadevices v0.3.2, github.com/pion/webrtc/v3 v3.1.10
  - Browser: Chrome 98.0.4
  - Other Information:
####  Stacktrace:

```
panic: send on closed channel

goroutine 369 [running]:
github.com/pion/mediadevices.(*baseTrack).unbind(0x3962393261333461, {{0xc00027c8d0, 0x20}, {{0x7ff693bfa658, 0x0, 0x0}, {0xc000f00000, 0x1, 0x1}}, 0xec9d1d4, ...})
	$GOPATH/pkg/mod/github.com/pion/mediadevices@v0.3.2/track.go:227 +0x70
github.com/pion/mediadevices.(*VideoTrack).Unbind(0x0, {{0xc00027c8d0, 0x20}, {{0x7ff693bfa658, 0x0, 0x0}, {0xc000f00000, 0x1, 0x1}}, 0xec9d1d4, ...})
	$GOPATH/pkg/mod/github.com/pion/mediadevices@v0.3.2/track.go:311 +0x45
github.com/pion/webrtc/v3.(*RTPSender).ReplaceTrack(0xc00016c2c0, {0x0, 0x0})
	$GOPATH/pkg/mod/github.com/pion/webrtc/v3@v3.1.10/rtpsender.go:157 +0x198
github.com/pion/webrtc/v3.(*RTPSender).Stop(0xc00016c2c0)
	$GOPATH/pkg/mod/github.com/pion/webrtc/v3@v3.1.10/rtpsender.go:240 +0x85
github.com/pion/webrtc/v3.(*RTPTransceiver).Stop(0xc00019a510)
	$GOPATH/pkg/mod/github.com/pion/webrtc/v3@v3.1.10/rtptransceiver.go:148 +0x7e
github.com/pion/webrtc/v3.(*PeerConnection).Close(0xc000029200)
	$GOPATH/pkg/mod/github.com/pion/webrtc/v3@v3.1.10/peerconnection.go:1878 +0x1c5
gitlab.com/awati/vrp-server/peerconnection.CloseConnection(0xc0000a3fd0, 0x23c)
	$PROJECT_FOLDER/peerconnection/peerconnection.go:360 +0x148
gitlab.com/awati/vrp-server/peerconnection.StartEngine.func1(0x5)
	$PROJECT_FOLDER/peerconnection/peerconnection.go:117 +0x48
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange
	$GOPATH/pkg/mod/github.com/pion/webrtc/v3@v3.1.10/peerconnection.go:488 +0x175
```

### What did you do?
I call a close function when the state changes to some imcompatible status:
```go
 peerConnection.OnConnectionStateChange(func(pcs webrtc.PeerConnectionState) {
 	switch pcs {
	case webrtc.PeerConnectionStateDisconnected, webrtc.PeerConnectionStateClosed, webrtc.PeerConnectionStateFailed:
 		CloseConnection(peerConnection, pid)
 		fallthrough
 		...
```
and inside the CloseConnection i call peerConnection.Close()

### What did you expect?
To close the connection and continue to run the program
 
### What happened?
the process end with a panic message

### PR DESCRIPTION
**Pull request by EmrysMyrddin**
#### Description

Closing a record session on macOS does not close the reader.

This PR fixes this by closing the channel used to read incoming video frames directly in the Close function.
Calling it in the data callback is not working because since the record session is closed, the callback will never be called again. So the reader will indefinitely wait for a incoming frame/the channel to be closed, which will never happen.

By fixing this, i have also discover a bug, where closing a peer connection with some tracks already closed triggers a panic due to the stop mechanism.

#### Reference issue
Fixes #379

### CODE REVIEW

File: pkg/avfoundation/avfoundation_darwin.go [hunk 1]
```diff
@@ -118,8 +118,8 @@ func (rc *ReadCloser) dataCb(data []byte) {
 		return
 	}
 	select {
+	// Use the Done channel to avoid waiting for new data from closed camera
 	case <-rc.cancelCtx.Done():
-		close(rc.dataChan)
 	case rc.dataChan <- data:
```
Comment (at-wat) [inline pkg/avfoundation/avfoundation_darwin.go:123]: Won't it cause `send to closed channel` when `Close()` while running?

Comment (EmrysMyrddin) [reply pkg/avfoundation/avfoundation_darwin.go:123]: You are right, if the context is marked as done, the result of this select is random, can be both ok or panic.
I probably just had lot of luck when tested it ^^

I will search a better way to handle this.

Comment (EmrysMyrddin) [reply pkg/avfoundation/avfoundation_darwin.go:123]: Ok, after some tests, it's not luck.

We cancel the context before closing the channel, so the `case <-rc.cancelCtx.Done():` branch will always be triggered before the write on closed channel.

I can unregister the callback before closing the channel if you want but it shouldn't change any thing since we also check for the context not being canceled at the start of the callback.

Comment (at-wat) [reply pkg/avfoundation/avfoundation_darwin.go:123]: I wrote a simplified test and it seems panic at low probability.
```go
package main

import (
  "context"
  "sync"
  "testing"
)

func TestMain(t *testing.T) {
  const n = 1000000
  var nPanic int
  for i := 0; i < n; i++ {
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Errorf("Panic: %v", r)
          nPanic++
        } 
      }()
      ch := make(chan struct{})
      ctx, cancel := context.WithCancel(context.Background())

      var wg sync.WaitGroup

      wg.Add(1)
      go func() {
        cancel()
        close(ch)
        wg.Done()
      }()

      select {
      case ch <- struct{}{}:
      case <-ctx.Done():
      }
      wg.Wait()
    }()
  }
  if nPanic > 0 {
    t.Fatalf("panic %d/%d", nPanic, n)
  } 
}
```
Around 20/1000000 on my environment

Comment (at-wat) [reply pkg/avfoundation/avfoundation_darwin.go:123]: I think this logic is used all over the pion code.
It would be ok to merge this for now to avoid larger problem, but better to have safe logic.

Comment (EmrysMyrddin) [reply pkg/avfoundation/avfoundation_darwin.go:123]: Ok, will try to avoid this.

My idea is to use a WaitingGroup to be sure every callbacks have returned and that I can safely close the channel.
What do you think ?

Comment (at-wat) [reply pkg/avfoundation/avfoundation_darwin.go:123]: Sounds good to me!

File: pkg/avfoundation/avfoundation_darwin.go [hunk 2]
```diff
@@ -141,6 +147,8 @@ func (rc *ReadCloser) Close() {
 		rc.onClose()
 	}
 	rc.cancelFunc()
+	rc.closeWG.Wait()
+	close(rc.dataChan)
 	unregister(rc.id)
```
Comment (at-wat) [inline pkg/avfoundation/avfoundation_darwin.go:152]: I believe current code fixes all cases, but would be better to put unregister first to reduce unnecessary call which is aborted by `rc.cancelCtx.Err()` check.

Comment (EmrysMyrddin) [reply pkg/avfoundation/avfoundation_darwin.go]: Shouldn't we also close something to avoid the callback being called at all ? I mean, unregister will just silence the the fact we receive data right ?

Comment (EmrysMyrddin) [reply pkg/avfoundation/avfoundation_darwin.go]: Ho ok, it's because we close the avfoundation session in the code calling this close function.

**Review by at-wat — APPROVED** [review]
LGTM
