### PR TITLE
Fix dead lock when closing peer connection with running tracks

### LINKED ISSUE #336: Dead lock on closing Peer Connection while media device track running
### Your environment.
  - Version: v0.2.0
  - Browser: none

### What did you do?
I have started a peer connection with a media device track sending camera video feed.
Call `Close` method on the peer connection.

### What did you expect?
Calling `Close` should close the connection as expected

### What happened?
Calling `Close` causes a dead lock.

The reason of the dead lock is a double lock request on the same mutex by both the track closing code and the track error handling code.

### PR DESCRIPTION
**Pull request by EmrysMyrddin**
#### Description
The `unbind` function was borrowing the track mutex more than it should. We need to borrow only while searching for active peer connection.

Keeping the lock while waiting for the end of the peer connection leads to dead lock with other parts of the code such as track's error handling code.

#### Reference issue
Fixes #336

### CODE REVIEW

**Review by lherman-cs — APPROVED** [review]
Good catch, thanks!!

File: track.go [hunk 1]
```diff
@@ -209,21 +209,30 @@ func (track *baseTrack) bind(ctx webrtc.TrackLocalContext, specializedTrack Trac
...
-	ch, ok := track.activePeerConnections[ctx.ID()]
-	if !ok {
-		return errNotFoundPeerConnection
+	ch, err := track.removeActivePeerConnection(ctx.ID())
+	if err != err {
+		return err
 	}
 
 	doneCh := make(chan struct{})
 	ch <- doneCh
```
Comment (itzmanish) [inline track.go:218]: Just a small question why are you doing this?
If you want to close a channel then you can do close(ch) instead.

File: track.go [hunk 2]
```diff
@@ -209,21 +209,30 @@ func (track *baseTrack) bind(ctx webrtc.TrackLocalContext, specializedTrack Trac
...
 	<-doneCh
```
Comment (itzmanish) [inline track.go:219]: I don't understand the use of doneCh and getting from empty doneCh.

File: track.go (hunk 1 above)
Comment (at-wat) [reply track.go:218]: https://github.com/pion/mediadevices/blob/b3c94a1f7bc2a1ef43c4056258269083a7e760f5/track.go#L174-L192
`doneCh` is sent to a routine created by `bind()` through `ch` and the routine closes the `doneCh` after finishing the loop.
`<-doneCh` waits until finishing the loop.

Comment (itzmanish) [reply track.go:218]: Yep. Makes sense.

File: track.go (hunk 2 above)
Comment (itzmanish) [reply track.go:219]: I am finding it difficult to understand that won't line 221 creates an error like `fatal error: all goroutines are asleep - deadlock!`? And line 222 will wait for forever since there is nothing in doneCh which will create deadlock situation.

Comment (itzmanish) [reply track.go:219]: https://play.golang.org/p/QufENXCZpO-

Comment (at-wat) [reply track.go:219]: https://play.golang.org/p/qBdpOKwdorR
as written in https://github.com/pion/mediadevices/pull/337#discussion_r739964814

Comment (itzmanish) [reply track.go:219]: Nice. This is a cool trick. Thanks @at-wat , lesson learned. 😃
